#!/usr/bin/env bash

OS_ID=$(awk -F'=' '/^ID=/{gsub(/"/, "", $2); print $2}' /etc/os-release)
echo "$OS_ID"

if [[ $1 == "--help" ]]; then
    echo "You can Pass arguments as this file"
    ls ./runs/$OS_ID
    exit 0
fi

for sc in "${@:1}"; do
    echo "ARG: $sc"
    script="$(ls ./runs/$OS_ID | grep $sc)"
    if [[ -z "$script" ]]; then
        echo "Only these scripts are available"
        ls ./runs/$OS_ID
        exit 0
    fi
    echo "GREP: $script"
    ./runs/$OS_ID/$script
    notify-send "Process Completed: $sc" "Ended with $(echo $?)"
done
