#!/usr/bin/env bash

if [ -z "$DEV_ENV" ]; then 
    echo "Env Var DEV_ENV is not present"
    exit 1
fi

export DEV_ENV="$DEV_ENV"

# Get which os you are using
OS_ID=$(awk -F'=' '/^ID=/{gsub(/"/, "", $2); print $2}' /etc/os-release)
echo "$OS_ID"

dry_run=0

log() {
    if [[ $dry_run -eq 1 ]]; then 
        echo "[DRY]: $1"
    else
        echo "$1"
    fi
}

if [[ $1 == "--help" ]]; then
    echo "You can Pass arguments as this file"
    ls ${DEV_ENV}/runs/$OS_ID
    exit 0
fi

for sc in "${@:1}"; do
    echo "ARG: $sc"
    script="$(ls ${DEV_ENV}/runs/$OS_ID | grep $sc)"
    if [[ -z "$script" ]]; then
        echo "Only these scripts are available"
        ls ${DEV_ENV}/runs/$OS_ID
        exit 0
    fi

    log "running: $script"

    if [[ $dry_run == 0 ]]; then
        ${DEV_ENV}/runs/$OS_ID/$script
    fi

    notify-send "Process Completed: $sc" "Ended with $(echo $?)"
done
